services:
  - type: web
    name: neofly-downloader-api
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: export PATH=$PATH:$(pwd)/bin && gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    disk:
      name: neofly-tmp
      mountPath: /tmp
      sizeGB: 1
      
